#!/bin/zsh
# /context — attach reference documents (PDF, DOCX, XLSX, PPTX, MD, TXT, …)
# to the active project so /ask can read them.
#
# Two artefacts per imported doc, both in <project>/_context/:
#   <name>.md          — full converted markdown (kept for the Claude path
#                        and as the source of truth)
#   <name>.summary.md  — ~500-token structured summary, generated by the
#                        active LLM backend. Used by the local /ask path
#                        when the full doc would exceed the model's
#                        context window. Skipped if the converted .md
#                        is already short (< CONTEXT_SUMMARY_THRESHOLD).
#
# Sourced by bin/meetink AFTER summary.sh, repl.sh. Depends on:
#   - $MK_HOME, $MK_ROOT, $MK_PY_VENV (set in bin/meetink)
#   - $MK_TRANSCRIPTS_DIR (set in bin/meetink, project-resolved)
#   - title_backend_active, claude_model_active, llm_path,
#     local_llm_active_get  (defined in titling.sh)
#   - C[] from ui.sh

# Don't bother summarizing docs shorter than this many tokens — the summary
# would be longer than the source. Threshold is conservative.
CONTEXT_SUMMARY_THRESHOLD="${MEETINK_CONTEXT_SUMMARY_THRESHOLD:-800}"


# Per-quant token budget for the local /ask path. Mirrors _ASK_TOKEN_BUDGETS
# in src/repl/repl.py — keep them in sync. The local path reserves 600
# tokens for response, so the *available* budget for context is slightly
# smaller, but for the /context list overshoot warning we compare against
# the model's effective budget (matches what the user sees in the footer
# context-bar chip).
_local_budget_tokens() {
    local m="qwen3.5-2b"
    if typeset -f local_llm_active_get >/dev/null; then
        m=$(local_llm_active_get 2>/dev/null)
    fi
    case "$m" in
        qwen3.5-0.8b) print -n -- "8000" ;;
        qwen3.5-2b)   print -n -- "16000" ;;
        qwen3.5-4b)   print -n -- "16000" ;;
        qwen3.5-9b)   print -n -- "32000" ;;
        *)            print -n -- "8000" ;;
    esac
}

# Approximate window for the active Claude model. Standard 4.x ships at
# 200K; the [1m] extended-window variants take 1M. Mirrors _claude_budget
# in src/repl/repl.py.
_claude_budget_tokens() {
    local m="claude-sonnet-4-6"
    if typeset -f claude_model_active >/dev/null; then
        m=$(claude_model_active 2>/dev/null)
    fi
    if [[ "${m:l}" == *1m* ]]; then
        print -n -- "1000000"
    else
        print -n -- "200000"
    fi
}

# Format a budget value as a compact human label: 200000 → 200K, 1000000 → 1M.
_human_budget() {
    local b=$1
    if (( b >= 1000000 )); then
        print -n -- "$((b / 1000000))M"
    elif (( b >= 1000 )); then
        print -n -- "$((b / 1000))K"
    else
        print -n -- "$b"
    fi
}

# Render "<colored pct>% of <budget> · <model>[ ⚠ overshoot]" given:
#   $1 = used tokens   $2 = budget   $3 = model label
_budget_chip() {
    local used=$1 budget=$2 label=$3
    if (( budget == 0 )); then
        print -n -- "${C[dim]}budget unknown${C[reset]}"
        return
    fi
    local pct=$((100 * used / budget))
    local colour
    if   (( pct < 50 )); then colour="${C[green]}"
    elif (( pct < 90 )); then colour="${C[yellow]}"
    else                       colour="${C[red]}"
    fi
    local hb=$(_human_budget $budget)
    local marker=""
    (( pct > 100 )) && marker="  ${C[red]}⚠ overshoot${C[reset]}"
    print -n -- "${colour}${pct}%${C[reset]} ${C[dim]}of ${hb} · ${label}${C[reset]}${marker}"
}


# Project's _context/ directory. Created on first /context add.
_context_dir() {
    print -n -- "$MK_TRANSCRIPTS_DIR/_context"
}


# Lazy install of markitdown into the REPL venv on first /context add.
# We use the format extras (`[pdf,docx,xlsx,pptx]`) rather than `[all]` so
# we skip the heavy audio + Azure deps the user almost certainly won't need.
_context_ensure_markitdown() {
    if [[ ! -x "$MK_PY_VENV/bin/python" ]]; then
        print -P "${C[red]}error:${C[reset]} REPL Python venv missing — run ${C[bright_cyan]}meetink setup${C[reset]} first"
        return 1
    fi
    if "$MK_PY_VENV/bin/python" -c "import markitdown" 2>/dev/null; then
        return 0
    fi
    if ! command -v uv >/dev/null 2>&1; then
        print -P "${C[red]}error:${C[reset]} uv not found — run ${C[bright_cyan]}meetink setup${C[reset]} first"
        return 1
    fi
    print -P "${C[bright_yellow]}▸${C[reset]} Installing markitdown ${C[dim]}(~80 MB with PDF/DOCX/XLSX/PPTX support)...${C[reset]}"
    if ! uv pip install --python "$MK_PY_VENV/bin/python" --quiet \
            "markitdown[pdf,docx,xlsx,pptx]"; then
        print -P "${C[red]}error:${C[reset]} markitdown install failed"
        return 1
    fi
    print -P "${C[green]}✓${C[reset]} markitdown installed"
}


# Ask the helper to count tokens of a file. Honours the active local
# model's tokenizer for accuracy; falls back to chars/4 estimate if the
# model snapshot isn't downloaded.
_context_token_count() {
    local file="$1"
    local model_path=""
    if typeset -f local_llm_active_get >/dev/null 2>&1; then
        model_path=$(llm_path "$(local_llm_active_get)" 2>/dev/null)
        [[ -f "$model_path/config.json" ]] || model_path=""
    fi
    "$MK_PY_VENV/bin/python" "$MK_ROOT/src/llm/context_helper.py" tokens \
        "$file" --model-path "$model_path" 2>/dev/null
}


# Slugify a doc name: lowercase, hyphens for spaces, strip extension.
_context_slugify() {
    local s="$1"
    s="${s:t:r}"           # strip dir + extension
    s="${s:l}"             # lowercase
    s="${s// /-}"          # spaces → hyphens
    s="${s//_/-}"          # underscores → hyphens
    # Drop anything that isn't alnum or hyphen
    s=$(print -- "$s" | tr -cd 'a-z0-9-')
    # Collapse runs of hyphens
    s=$(print -- "$s" | sed 's/-\{2,\}/-/g; s/^-\+//; s/-\+$//')
    [[ -z "$s" ]] && s="doc"
    print -n -- "$s"
}


# /context add <file> [name]
#
# Convert <file> to markdown, save as _context/<name>.md, and (if long
# enough) generate _context/<name>.summary.md via the active backend.
context_add() {
    local source="$1"
    local name="$2"

    if [[ -z "$source" ]]; then
        print -P "${C[red]}usage:${C[reset]} /context add <file> [name]"
        print -P "  ${C[dim]}Example:${C[reset]} /context add ~/Downloads/q3-strategy.pdf"
        return 1
    fi
    if [[ ! -f "$source" ]]; then
        print -P "${C[red]}error:${C[reset]} file not found: ${C[bold]}$source${C[reset]}"
        return 1
    fi

    # Derive name from filename if not given.
    [[ -z "$name" ]] && name=$(_context_slugify "$source")

    # If the source is already markdown / plain text, the helper takes a
    # passthrough path that doesn't need markitdown. Skip the ~80 MB install
    # in that case — saves bandwidth and the "Installing markitdown" prompt.
    local ext="${source:e:l}"
    local is_plain=0
    case "$ext" in
        md|markdown|txt) is_plain=1 ;;
    esac

    if (( ! is_plain )); then
        _context_ensure_markitdown || return 1
    fi

    local dir=$(_context_dir)
    mkdir -p "$dir"

    local target="$dir/${name}.md"
    if [[ -f "$target" ]]; then
        print -P "${C[bright_yellow]}⚠${C[reset]}  ${C[bold]}$name${C[reset]} already exists at ${target/$HOME/~}"
        print -nP "  Overwrite? ${C[dim]}(y/N)${C[reset]}: "
        local confirm; read confirm
        [[ "$confirm" != "y" && "$confirm" != "Y" ]] && {
            print -P "${C[dim]}cancelled${C[reset]}"; return 1
        }
    fi

    if (( is_plain )); then
        print -P "${C[bright_yellow]}▸${C[reset]} Importing ${C[bold]}${source:t}${C[reset]}..."
    else
        print -P "${C[bright_yellow]}▸${C[reset]} Converting ${C[bold]}${source:t}${C[reset]} → markdown..."
    fi
    if ! "$MK_PY_VENV/bin/python" "$MK_ROOT/src/llm/context_helper.py" \
            convert "$source" --output "$target"; then
        print -P "${C[red]}error:${C[reset]} conversion failed"
        rm -f "$target"
        return 1
    fi

    local tokens=$(_context_token_count "$target")
    print -P "${C[green]}✓${C[reset]} Saved ${C[bold]}${name}.md${C[reset]} ${C[dim]}(${tokens} tokens)${C[reset]}"

    # Skip summarization for short docs — the summary would be longer than
    # the source. The full file is still picked up by /ask.
    if (( tokens < CONTEXT_SUMMARY_THRESHOLD )); then
        print -P "  ${C[dim]}(short — no summary needed; full doc fits in any backend)${C[reset]}"
        return 0
    fi

    # Generate summary with the active backend, mirroring per-meeting summary
    # behaviour. Best-effort; failure leaves the .md in place.
    local backend=$(title_backend_active)
    local model_label model_path=""
    case "$backend" in
        claude)
            if ! command -v claude >/dev/null 2>&1; then
                print -P "  ${C[yellow]}⚠${C[reset]} backend=claude but claude CLI not found — skipping summary"
                return 0
            fi
            model_label=$(claude_model_active)
            ;;
        lmstudio)
            if ! _lmstudio_available; then
                print -P "  ${C[yellow]}⚠${C[reset]} LM Studio not reachable — skipping summary"
                return 0
            fi
            model_label=$(lmstudio_model_resolve 2>/dev/null)
            ;;
        *)
            model_label=$(local_llm_active_get)
            model_path=$(llm_path "$model_label")
            if [[ ! -f "$model_path/config.json" ]]; then
                print -P "  ${C[yellow]}⚠${C[reset]} local model not downloaded — skipping summary"
                return 0
            fi
            backend="local"
            ;;
    esac

    local summary_target="$dir/${name}.summary.md"
    print -P "${C[bright_yellow]}▸${C[reset]} Generating summary via ${C[bold]}${model_label}${C[reset]}..."
    if "$MK_PY_VENV/bin/python" "$MK_ROOT/src/llm/context_helper.py" \
            summarize "$target" \
            --output "$summary_target" \
            --backend "$backend" \
            --model "$model_label" \
            --model-path "$model_path" \
            --endpoint "$(lmstudio_endpoint)"; then
        local s_tokens=$(_context_token_count "$summary_target")
        print -P "${C[green]}✓${C[reset]} Summary written ${C[dim]}(${s_tokens} tokens)${C[reset]}"
    else
        print -P "  ${C[yellow]}⚠${C[reset]} summary failed — full doc still available"
        rm -f "$summary_target"
    fi
}


# /context list
context_list() {
    local dir=$(_context_dir)
    if [[ ! -d "$dir" ]]; then
        print -P "${C[dim]}No context docs in this project yet.${C[reset]}"
        print -P "  Add one with ${C[bright_cyan]}/context add <file>${C[reset]}"
        return 0
    fi
    setopt local_options null_glob
    local -a docs=("$dir"/*.md(.))
    # Filter out summary files — they're listed alongside their parents.
    local -a primary=()
    local f
    for f in "${docs[@]}"; do
        [[ "$f" == *.summary.md ]] && continue
        primary+=("$f")
    done
    if (( ${#primary[@]} == 0 )); then
        print -P "${C[dim]}No context docs in this project yet.${C[reset]}"
        return 0
    fi

    print -P ""
    print -P "${C[bright_yellow]}CONTEXT DOCS${C[reset]} ${C[dim]}(in ${dir/$HOME/~})${C[reset]}"
    print -P ""

    local total_full=0 total_summary=0
    for f in "${primary[@]}"; do
        local name="${f:t:r}"
        local source=$(awk '/^---/{c++; if(c>=2) exit; next} c==1 && /^source:/ {sub(/^source:[[:space:]]*/,""); print; exit}' "$f")
        local tokens=$(_context_token_count "$f")
        total_full=$((total_full + tokens))
        local sumf="$dir/${name}.summary.md"
        if [[ -f "$sumf" ]]; then
            local stok=$(_context_token_count "$sumf")
            total_summary=$((total_summary + stok))
            local gen=$(awk '/^---/{c++; if(c>=2) exit; next} c==1 && /^generated_by:/ {sub(/^generated_by:[[:space:]]*/,""); print; exit}' "$sumf")
            printf "  ${C[bold]}%-24s${C[reset]} ${C[dim]}%-20s%6s tok · summary %4s tok ${C[reset]}${C[dim]}(${gen})${C[reset]}\n" \
                "$name" "${source:-(unknown)}" "$tokens" "$stok"
        else
            total_summary=$((total_summary + tokens))   # no summary → use full
            printf "  ${C[bold]}%-24s${C[reset]} ${C[dim]}%-20s%6s tok · ${C[reset]}${C[dim]}no summary (short)${C[reset]}\n" \
                "$name" "${source:-(unknown)}" "$tokens"
        fi
    done
    # Budget chips compare the totals against the active backend's window
    # so the user sees at a glance whether their attached docs fit. Each row
    # measures the path that actually consumes that total: the claude path
    # uses the full markdown, the local path uses summaries.
    local local_budget=$(_local_budget_tokens)
    local local_label="qwen3.5-2b"
    if typeset -f local_llm_active_get >/dev/null; then
        local_label=$(local_llm_active_get 2>/dev/null)
    fi
    local claude_budget=$(_claude_budget_tokens)
    local claude_label="Sonnet"
    if typeset -f claude_model_active >/dev/null; then
        claude_label=$(claude_model_active 2>/dev/null)
    fi

    # Use plain `print --` (not `print -P`) for the budget rows: the chip
    # output contains literal `%` characters (the percentage), which `print -P`
    # would treat as the start of a prompt escape and consume the following
    # `\033` byte — leaving "[0m" as visible literal text.
    print -P ""
    print -r -- "  ${C[dim]}Total full:${C[reset]}     ${total_full} tokens · $(_budget_chip $total_full $claude_budget $claude_label) ${C[dim]}(claude path)${C[reset]}"
    print -r -- "  ${C[dim]}Total compact:${C[reset]}  ${total_summary} tokens · $(_budget_chip $total_summary $local_budget $local_label) ${C[dim]}(local path)${C[reset]}"
    print -P ""
    print -P "  ${C[dim]}/context add <file>${C[reset]}     ${C[dim]}/context show <name>${C[reset]}     ${C[dim]}/context rm <name>${C[reset]}"
    print -P ""
}


# /context rm <name>
context_remove() {
    local name="$1"
    if [[ -z "$name" ]]; then
        print -P "${C[red]}usage:${C[reset]} /context rm <name>"
        return 1
    fi
    local dir=$(_context_dir)
    local md="$dir/${name}.md"
    local sumf="$dir/${name}.summary.md"
    if [[ ! -f "$md" && ! -f "$sumf" ]]; then
        print -P "${C[dim]}${name}: not found${C[reset]}"
        return 0
    fi
    [[ -f "$md" ]] && rm -f "$md"
    [[ -f "$sumf" ]] && rm -f "$sumf"
    print -P "${C[green]}✓${C[reset]} Removed ${C[bold]}$name${C[reset]}"
}


# /context show <name>
context_show() {
    local name="$1"
    if [[ -z "$name" ]]; then
        print -P "${C[red]}usage:${C[reset]} /context show <name>"
        return 1
    fi
    local target="$(_context_dir)/${name}.md"
    if [[ ! -f "$target" ]]; then
        print -P "${C[red]}error:${C[reset]} ${C[bold]}$name${C[reset]} not found"
        print -P "  Run ${C[bright_cyan]}/context list${C[reset]} to see what's available."
        return 1
    fi
    cat "$target"
}


# /context dispatcher
cmd_context() {
    local sub="$1"
    case "$sub" in
        ""|status|list|ls)
            context_list
            ;;
        add|import|upload)
            context_add "$2" "$3"
            ;;
        rm|remove|delete)
            context_remove "$2"
            ;;
        show|cat|view)
            context_show "$2"
            ;;
        *)
            print -P "${C[red]}unknown:${C[reset]} ${C[dim]}/context $sub${C[reset]}"
            print -P "  ${C[dim]}/context${C[reset]} | ${C[dim]}/context add <file>${C[reset]} | ${C[dim]}/context rm <name>${C[reset]} | ${C[dim]}/context show <name>${C[reset]}"
            ;;
    esac
}
